package com.xiting.a4e.model.structures;

public class AlAuthBasicStr {
	public final static String LINE = "LINE";
	public final static String SCOPETYPE = "SCOPETYPE";
	public final static String AL_OBJECT = "AL_OBJECT";
	public final static String FLAG = "FLAG";
	public final static String CALLSTACK = "CALLSTACK";
	public final static String OBJECT = "OBJECT";
	public final static String FIELD01 = "FIELD01";
	public final static String VAL01 = "VAL01";
	public final static String FLAG01 = "FLAG01";
	public final static String FIELD02 = "FIELD02";
	public final static String VAL02 = "VAL02";
	public final static String FLAG02 = "FLAG02";
	public final static String FIELD03 = "FIELD03";
	public final static String VAL03 = "VAL03";
	public final static String FLAG03 = "FLAG03";
	public final static String FIELD04 = "FIELD04";
	public final static String VAL04 = "VAL04";
	public final static String FLAG04 = "FLAG04";
	public final static String FIELD05 = "FIELD05";
	public final static String VAL05 = "VAL05";
	public final static String FLAG05 = "FLAG05";
	public final static String FIELD06 = "FIELD06";
	public final static String VAL06 = "VAL06";
	public final static String FLAG06 = "FLAG06";
	public final static String FIELD07 = "FIELD07";
	public final static String VAL07 = "VAL07";
	public final static String FLAG07 = "FLAG07";
	public final static String FIELD08 = "FIELD08";
	public final static String VAL08 = "VAL08";
	public final static String FLAG08 = "FLAG08";
	public final static String FIELD09 = "FIELD09";
	public final static String VAL09 = "VAL09";
	public final static String FLAG09 = "FLAG09";
	public final static String FIELD10 = "FIELD10";
	public final static String VAL10 = "VAL10";
	public final static String FLAG10 = "FLAG10";

	public int line;
	public String scopetype;
	public AlObjectStr alObject;
	public String flag;
	public String callstack;
	public String object;
	public String field01;
	public String val01;
	public String flag01;
	public String field02;
	public String val02;
	public String flag02;
	public String field03;
	public String val03;
	public String flag03;
	public String field04;
	public String val04;
	public String flag04;
	public String field05;
	public String val05;
	public String flag05;
	public String field06;
	public String val06;
	public String flag06;
	public String field07;
	public String val07;
	public String flag07;
	public String field08;
	public String val08;
	public String flag08;
	public String field09;
	public String val09;
	public String flag09;
	public String field10;
	public String val10;
	public String flag10;

}
